### PR TITLE
Fix NPE on fill of non-existent JIRA.

### PR DESCRIPTION
**Pull request by abayer**
cc @reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by oleg-nenashev** [comment]
:bee: 
Would be great to finally move this project to jenkinsci-infra ORG. Is there an INFRA task for this issue?

**Comment by abayer** [comment]
Not that I'm aware of, but feel free to throw one at me. =)

**Comment by abayer** [comment]
Ok, now there _is_ a JIRA. https://issues.jenkins-ci.org/browse/INFRA-528

**Comment by andresrc** [comment]
:bee:

**Comment by abayer** [comment]
@reviewbybees done

**Comment by ghost** [comment]
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

**Pull request merged**
