### PR TITLE
Delete 'generate-rc-announcement' script

### PR DESCRIPTION
**Pull request by NotMyFault**
`xdg` isn't shipped on macOS and hard to obtain. The change proposed moves to `open mailto:...` opening the configured mail client of your choice, independent of the OS.

`/usr/bin/date` has been replaced with `date` because the path specified is not available on macOS.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
bits on line 8 is also never going to work

not sure how useful this script is 👅

**Comment by NotMyFault** [comment]
> not sure how useful this script is 👅

My CMD+C/CMD+V buttons work very well when posting on the mailing list 😌 

Haven't used that script since I do LTS releases because it never worked for me and prior was faster, but I thought maybe someone else does 🤷

**Comment by timja** [comment]
I tried it the first time when it was handed over to me, ran away because it was linux specific and I do the same as you.
I doubt anyone uses this and I would suggest just deleting it.

especially because you have to check the date anyway 🤷

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
Actually, thoughts about flattening this repository and moving the scripts we actually need into https://github.com/jenkins-infra/release/tree/master/docs ?

**Comment by timja** [comment]
> Actually, thoughts about flattening this repository and moving the scripts we actually need into [jenkins-infra/release@`master`/docs](https://github.com/jenkins-infra/release/tree/master/docs?rgh-link-date=2023-05-31T15%3A21%3A00Z) ?

agreed

**Pull request closed without merging**
